#! ---------------------------------------------------------------
#! Obsidian theme use manual highlight.js
#! To maintain the code block css display properly
#! please change your default highlight setting as off!!
#! Rebuild files after you changed the config:
#! `hexo clean && hexo g`
#! ---------------------------------------------------------------
#! highlight:
#!  enable: false
#!  line_number: true
#!  auto_detect: true
#!  tab_replace:
#! ---------------------------------------------------------------

# Theme version
version: "1.3.4"

# ---------------------------------------------------------------
# Theme default settings
# ---------------------------------------------------------------

# Menu setting | format = title_name: link_url
menu:
  ABOUT: /whoami
  CATEGORIES: /categories
  TAGS: /tags
  ARCHIVES: /archives

# Social media links
socials:
  github: "https://github.com/Sicmatr1x"
  twitter: ""
  stackoverflow: ""

# Enable table of content
TOC: true

# Home page first post default cover image, default use cover
welcome_cover: /img/welcome-cover.jpg

# Article default cover image
cover: /img/cover.jpg

# Avatar
avatar: /img/ETO.png

# Disable default scrollbar
scrollbar: true

# Website keywords used for SEO
keywords: Sicmatr1x

# Website slogans
descriptionOne: "Reason is a tiny spark in the dark night, a precious exception in the crazy world."
descriptionTwo: "理智是慢慢黑夜里的一个微小的火花，是疯狂的世界里的一个珍贵的例外"

# If you use google analytics, please fill in the ID
google_analytics: ''

# Website favicon
favicon: /img/ETO.png

# rss file
rss: atom.xml

# ---------------------------------------------------------------
# Article Music settings
# ---------------------------------------------------------------

# Auto play article audio
autoplay: false

# default mp3 file
mp3:
  - statics/A Cruel Angel's Thesis Bilingual two-channel effects version.mp3

# ---------------------------------------------------------------
# Plugins
# ---------------------------------------------------------------

# Gitalk comment plugin
# see https://github.com/gitalk/gitalk
gitalk:
  enable: true
  autoExpand: true
  clientID: 'db290dc011893521d885'
  clientSecret: '4cbc64d2114f4963d8090a55b508568b2f26075b'
  repo: 'blog-comments'
  owner: 'Sicmatr1x'
  admin: ['Sicmatr1x']
  # Ensure uniqueness and length less than 50
  id: location.pathname
  # Facebook-like distraction

# Valine comment plugin (recommended!)
# see https://valine.js.org/quickstart.html
valine:
  enable: false
  app_id:
  app_key:
  notify: false
  verify: false
  avatar: 'mp'
  placeholder: 'Leave your throughs behind~'
  visitor: true

# Enable symbols-count-time plugin
# see https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  enable: true
  wordCount: true
  readCount: true
  awl: 4
  wpm: 275
  suffix: mins.

# Enable html truncate
# see https://github.com/TriDiamond/hexo-html-truncate
html_truncate:
  enable: true
  # Characters kept for posts
  postLength: 250
  # Characters kept for cover posts
  coverLength: 100
  ellipsis: '...'
  # Excluding html tags
  excludes: ['img', 'h1', 'h2']
  # Characters count including white spaces
  keepWhitespaces: true
  # Reserving the last complete word, without breaking the word
  reserveLastWord: true

# Enable Busuanzi statistic plugin
# see http://ibruce.info/2015/04/04/busuanzi/
busuanzi:
  enable: true

#Enable social media sharing
sharejs:
  enable: true
  disabled: 'facebook,douban,linkedin,diandian,tencent,google'
